[theme]

# olive green #606c38
# mustard yellow #dda15e
# dark forest green  #283618

# interactive 
primaryColor = "#dda15e" 
backgroundColor = "#283618"
secondaryBackgroundColor = "#606c38"

# Color used for almost all text (alternatives: #F1FAEE, #e7ecef)
textColor = "#e7ecef"
