[theme]

# color palatte
    # olive green #606c38
    # mustard yellow #dda15e
    # dark forest green #283618
    # morning mist #E7ECEF

# the interactive elements
primaryColor = "#dda15e" 
# main background color
backgroundColor = "#283618"
# sidebar, text boxes
secondaryBackgroundColor = "#606c38"

# text (alternatives: #F1FAEE, #404242)
textColor = "E7ECEF"
